name: Build DEB Package with /packaging

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make packaging scripts executable
        run: chmod +x packaging/*.sh

      - name: Install dependencies from chkdeps.sh
        run: |
          cd packaging
          sudo apt-get update
          sudo apt-get install -y $(./chkdeps.sh -l | cut -d':' -f2 | tr '\n' ' ')

      - name: Build project using packaging/buildall.sh
        run: |
          cd packaging
          ./buildall.sh -t deb
      - name: List built packages
        run: ls -lh /packaging/xptc

      - name: Upload .deb packages as artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: built-debs
          path: packaging/xptc/*.deb
