name: Build DEB Package with /packaging

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make packaging scripts executable
        run: chmod +x packaging/*.sh

      - name: Install dependencies from chkdeps.sh
        run: |
          cd packaging
          sudo apt-get update
          sudo apt-get install -y $(./chkdeps.sh -l | cut -d':' -f2 | tr '\n' ' ') \
          libgdk-pixbuf-2.0-dev \
          libglib2.0-dev \
          libgtk-3-dev \
          liblightdm-gobject-1-dev \
          gettext \
          x11-apps \
          ruby-sass \
          libcanberra-dev \
          libcanberra-gtk3-dev \
          libwebkit2gtk-4.1-dev \
          libzip-dev \
          libgarcon-1-dev \
          libgarcon-gtk3-1-dev \
          libnm-dev \
          libupower-glib-dev \
          libpulse-dev


      - name: Build project using packaging/buildall.sh
        run: |
          cd packaging
          ./buildall.sh -t deb
      - name: Collect .deb packages from output
        run: |
          mkdir -p packaging/output
          cd packaging/xptc 
          cp {} packaging/output/ \;

      - name: List built packages
        run: ls -lh packaging/output

      - name: Upload .deb packages as artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-debs
          path: packaging/output/*.deb
